# Generated by Django 4.1 on 2022-09-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctions_alter_user_id_watchlist_comments_bids_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctions',
            name='category',
        ),
        migrations.AddField(
            model_name='auctions',
            name='image_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
