# Generated by Django 4.1 on 2022-09-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auctions_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='image_url',
            field=models.CharField(blank=True, default='https://demofree.sirv.com/nope-not-here.jpg', max_length=256, null=True),
        ),
    ]
